# Generated by Django 5.2.3 on 2025-07-16 08:24

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the Event', max_length=1000)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='events.contact')),
            ],
        ),
        migrations.CreateModel(
            name='EventInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular event across whole registry', primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('n', 'Normal'), ('c', 'Canceled'), ('p', 'Pending')], default='n', help_text='Event status', max_length=1)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='events.event')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What type of event is this', max_length=200, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='EventType_name_case_insensitive_unique', violation_error_message='Event type already exists (case insensitive match)')],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='EventType',
            field=models.ManyToManyField(help_text='Select a type for this Event', to='events.eventtype'),
        ),
    ]
