# Generated by Django 5.2.3 on 2025-07-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='EventType',
            new_name='type',
        ),
    ]
