# Generated by Django 5.1.6 on 2025-08-21 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventinstance_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinstance',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='max_followers',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of Followers per instance'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_leaders',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of Leaders per instance'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, help_text='Total maximum participants per instance'),
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('L', 'Leader'), ('F', 'Follower'), ('D', 'DoubleRole')], default='F', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('L', 'Leader'), ('F', 'Follower'), ('D', 'DoubleRole')], max_length=1)),
                ('event_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.eventinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'event_instance'), name='unique_user_eventinstance')],
            },
        ),
    ]
