# Generated by Django 5.1.6 on 2025-08-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_eventinstance_user_event_max_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinstance',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
