# Generated by Django 5.1.6 on 2025-08-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventinstance_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinstance',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
