# Generated by Django 5.1.6 on 2025-08-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventinstance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='approved',
            field=models.BooleanField(default=False, help_text='Whether this user is approved by staff'),
        ),
    ]
